### ISSUE TITLE
Support for dynamic library API

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/PythonRemoteServer#18]
Currently the remote server supports only static and hybrid APIs. Supporting also the dynamic API shouldn't be too complicated and would mean all library APIs are covered.

There exits an old pull request #1 that implements this functionality. Unfortunately changes done in 1.0 version mean that it cannot be anymore cleanly merged. I also have quite big refactoring plans for the code in general, and the approach in the pull request isn't compatible with them.

**Comment by rainmanwy** [comment]
Hi, Pekka

How about this issue, do you have plan to implement it?
i found "get_keyword_arguments" and "get_keyword_documentation" do not support dynamic libraries.

I am trying to implement a libraries which will expose some classes(Some protocols such as IP, TCP, ICMP which are implemented as python classes) as keywords to robot framework.

I have tried hybrid mode, these classes could not be imported as keywords as RF will check the type.

so i implement it as dynamic libraries, but it could not work with this remote server.

Do you have any suggestions about this?

**Comment by pekkaklarck** [comment]
So far this hasn't been important enough for anyone to provide a new PR or pay me or someone to implement it.

**Comment by pekkaklarck** [comment]
Did some refactoring to the code and one of the benefits was that adding dynamic library support became easier. I already got it mostly done.
