### ISSUE TITLE
how would i import the remote library in a python module

### ISSUE THREAD

**Issue by sanjeets** [robotframework/PythonRemoteServer#28]
I am trying 
server = xmlrpclib.Server(server_url)
and am getting an exception when trying to call a method for example:
ret = server.ComputeSum(var1,var2)

**Comment by pekkaklarck** [comment]
I don't understand what you are actually trying to do. That doesn't really matter because this issue tracker is for bug reports or enhancement requests. General questions are best sent to robotframework-users mailing list or other such forums.
