### ISSUE TITLE
report is not generated

### ISSUE THREAD

**Issue by kalyanreddyt** [robotframework/PythonRemoteServer#32]
Hi, we executed TCs via Jenkin and the execution was successful but got below error for report generation. Can someone please help how to resolve this issue

 raise DataError("Reading XML source '%s' failed: %s" % (unic(ets), error))
robot.errors.DataError: Reading XML source 'results\pabot_results\test.sample\fir.xml' failed: Incompatible XML element 'errors'.

**Comment by pekkaklarck** [comment]
Doesn't seem to be related to this tool.
