### ISSUE TITLE
"Strings Should Be Equal" should read as "Should Be Equal As Strings"

### ISSUE THREAD

**Issue by fireplume** [robotframework/PythonRemoteServer#34]
Thanks for the example. When trying it, I had an error and, after looking at the documentation, found that "Strings Should Be Equal" should read as "Should Be Equal As Strings".

**Comment by pekkaklarck** [comment]
No, the example library ought to create `Strings Should Be Equal` keyword. If using it fails, you most likely don't have the remove server hosting the example library running. There's `Should Be Equal As Strings` in the BuiltIn library, but that should not be used here.
