### ISSUE TITLE
Can I use nginx as a proxy?

### ISSUE THREAD

**Issue by JingYang0725** [robotframework/PythonRemoteServer#39]
Hello: 
         I would like to set up a number of remote services, the use of nginx proxy http rpc, I wonder if this is feasible?

Thank you！

**Comment by pekkaklarck** [comment]
I guess it should be. I know nothing about nginx, though.

Notice also that this tracker is for bug reports and enhancement requests. Support forums like robotramework-users mailing list are better for generic questions like this.
