### ISSUE TITLE
SyntaxError: invalid syntax for Python 3.6

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/PythonRemoteServer#40]
**Cite**: 'Remote server 1.1 and newer support Python 2.6, 2.7, 3.3, **and newer**.'

Python 3.6.0 on win32:
>>> import robotremoteserver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\robotremoteserver.py", line 103
    except (OSError, select.error), err:

SyntaxError: invalid syntax

**Comment by DirkRichter** [comment]
sorry. i tried 1.0.1 from pip...

**Comment by pekkaklarck** [comment]
Unfortunately this project got into a hold after implementing Python 3 support (#17) and 1.1 release is not out yet. I ought to have time for this project again this or next week and ought to get the release out soonish.
