### ISSUE TITLE
Cant run server with python modules

### ISSUE THREAD

**Issue by hallos** [robotframework/PythonRemoteServer#43]
Hello,
I am trying to run the server by passing a pythonmodule as library, as I understood it from the docs it should work.

But when I run some keywords from Robot framework the test just stalls and I have to force it to stop.

As soon as I edit my module and change it to a class it works.
It works to pass an objectinstance to RemoteServer and it works to pass a class as static with static methods.

I have an exisiting testlibrary that I would want to run with Robot framework so it would be nice to not have to change too much and be able to run it as an module.

The RemoteServer instance doesnt produce any output or debug messages so I cant give more detailed information at the moment.

If I had missunderstood the docs about support for module I am willing to look into it and try to add support if its something that would be interesting for you.

**Comment by pekkaklarck** [comment]
As you can see, I added an explicit test for using a module as a remote library in 724445d. I doubt the problem you are facing has anything to do with how it's implemented, but with the provided information it's impossible to know what's going on. Can you create a simple example demonstrating the problem?

**Comment by hallos** [comment]
I did some more experimenting and realized that my problem is probably lying elsewhere, sorry for that.
I have an external module imported in my own module and that one is causing the problem.
When I comment out the import of this other module I can call my keywords from Robot Framework via RemoteServer as usual.
Why I need to rewrite my module as a class to be able to import this module maybe hasnt got anything to do with RemoteServer.
Thanks for helping me ruling out that the import of modules wasnt the issue.

**Comment by pekkaklarck** [comment]
Great that you got it sorted out!
