### ISSUE TITLE
Changes None to ''

### ISSUE THREAD

**Issue by mkorpela** [robotframework/PythonRemoteServer#56]
Did some tests with remote lib. I just noticed that when running Easter in PythonRemoteServer the None parameter is changed to empty string.. And then "None shall pass" :(

**Comment by pekkaklarck** [comment]
The reason is that XML-RPC doesn't support None/null that well. I think support for it needs to be enabled on both ends of the connection, and Remote just decided to do `None` -> `""` conversion. I'm not against changing this, but someone needed to test would the change break something.

**Comment by mkorpela** [comment]
I think I’ll close this one. Just a random observation.
