### ISSUE TITLE
DeprecationWarning: "from collections import Mapping"

### ISSUE THREAD

**Issue by hleskien** [robotframework/PythonRemoteServer#58]
Hi,

I get this in Python 3.8:

`robotremoteserver.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working`
`  from collections import Mapping`

Kind regards

Holger

**Comment by pekkaklarck** [comment]
Needs to update imports when working with this project the next time. Unfortunately I haven't had time for this project lately and with RF 3.2 still being under development won't have time in the near future either.

**Comment by hleskien** [comment]
Your ACK is enough for me at the moment. Thank you!

**Comment by tirkarthi** [comment]
I have created https://github.com/robotframework/PythonRemoteServer/pull/59 to fix this. For Python 2 collections is used and for Python 3 collections.abc is used. The move was done in Python 3.4 to raise a deprecation so I assume Python 3.3 is not supported since it's EoL. Thanks.

**Comment by hleskien** [comment]
Thank you!

**Comment by pekkaklarck** [comment]
This fix is required with Python 3.10 where `from collections import Mapping` doesn't work anymore. Need to finally create a release with this fix.
