### ISSUE TITLE
After installing PythonRemoteServer, No remote file present

### ISSUE THREAD

**Issue by Gaurav21git** [robotframework/PythonRemoteServer#65]
Hi,

I tried to launch my test suites parallel on remote machines. I installed "pip install robotremoteserver" but after installation complete. I had checked Remote folder under site-packages but is showing only documentation file. Screenshot for reference.
![image](https://user-images.githubusercontent.com/43947717/89519789-87e5c680-d7fa-11ea-879a-73b98ddd19de.png)

I tried to execute my test case on remote machine but it throwing exception below:

Getting keyword names from library 'Remote' failed: Calling dynamic method 'get_keyword_names' failed: Connecting remote server at http://192.168.56.1:5567 failed: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Please provide some solution to run test cases parallel on different machines.

Thanks,

**Comment by pekkaklarck** [comment]
The remote server is installed as a single `pythonremoteserver.py` file. The error indicates that the remote server cannot be accessed from the machine running Robot.
